# Generated by Django 4.1.6 on 2023-03-10 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Car",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("car_brand", models.CharField(max_length=50)),
                ("model", models.CharField(max_length=50)),
                ("charge_type", models.CharField(max_length=100)),
                ("horse_power", models.IntegerField()),
                ("num_sits", models.IntegerField()),
                ("range_km", models.IntegerField()),
                ("rent_price", models.FloatField()),
                ("year", models.IntegerField()),
                ("image", models.ImageField(upload_to="car_images")),
                ("description", models.TextField()),
            ],
        ),
    ]
