# Generated by Django 4.1.6 on 2023-03-10 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("EV_rent", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="car",
            name="url_page",
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="car",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="EV_rent"),
        ),
    ]
