# Generated by Django 4.1.6 on 2023-03-24 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("EV_rent", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="rentalrequest",
            name="is_broken",
            field=models.BooleanField(default=False),
        ),
    ]
