# Generated by Django 4.1.6 on 2023-03-11 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("EV_rent", "0002_car_url_page_alter_car_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="ServiceRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("car_model", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("photos", models.ImageField(blank=True, upload_to="service_requests")),
            ],
        ),
    ]
