# Generated by Django 4.1.6 on 2023-03-27 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("EV_rent", "0005_rentalrequest_is_rented_servicerequest_is_broken_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="car", name="description_en", field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="car", name="description_ru", field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="servicerequest",
            name="description_en",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="servicerequest",
            name="description_ru",
            field=models.TextField(null=True),
        ),
    ]
