# Generated by Django 4.1.6 on 2023-03-28 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("EV_rent", "0006_car_description_en_car_description_ru_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CarBrandAndYear",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("car_brand", models.CharField(max_length=50)),
                ("year", models.IntegerField()),
            ],
        ),
    ]
