# Generated by Django 4.1.6 on 2023-03-28 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("EV_rent", "0007_carbrandandyear"),
    ]

    operations = [
        migrations.DeleteModel(name="CarBrandAndYear",),
    ]
