# Generated by Django 4.1.6 on 2023-03-28 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("EV_rent", "0008_delete_carbrandandyear"),
    ]

    operations = [
        migrations.CreateModel(
            name="CarBrand",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("car_brand", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="CarYear",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
        ),
    ]
