# Generated by Django 4.1.6 on 2023-03-28 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("EV_rent", "0009_carbrand_caryear"),
    ]

    operations = [
        migrations.AddField(
            model_name="caryear",
            name="year",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
