# Generated by Django 4.1.6 on 2023-03-29 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("EV_rent", "0011_alter_car_url_page"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="carbrand",
            options={"verbose_name": "Марка", "verbose_name_plural": "Марки"},
        ),
        migrations.AlterModelOptions(
            name="caryear",
            options={"verbose_name": "Год машины", "verbose_name_plural": "Год машин"},
        ),
        migrations.CreateModel(
            name="Cars",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("model", models.CharField(max_length=50)),
                ("charge_type", models.CharField(max_length=100)),
                ("horse_power", models.IntegerField()),
                ("num_sits", models.IntegerField()),
                ("range_km", models.IntegerField()),
                ("rent_price", models.FloatField()),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="image_cars"),
                ),
                ("description", models.TextField()),
                ("url_page", models.SlugField(unique=True)),
                ("is_broken", models.BooleanField(default=False)),
                ("is_rented", models.BooleanField(default=False)),
                (
                    "car_brand",
                    models.ManyToManyField(
                        related_name="car_brand_mm",
                        to="EV_rent.carbrand",
                        verbose_name="Марка",
                    ),
                ),
                (
                    "year",
                    models.ManyToManyField(
                        related_name="car_year",
                        to="EV_rent.carbrand",
                        verbose_name="Год",
                    ),
                ),
            ],
        ),
    ]
