# Generated by Django 4.1.6 on 2023-03-29 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("EV_rent", "0012_alter_carbrand_options_alter_caryear_options_cars"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cars",
            name="year",
            field=models.ManyToManyField(
                related_name="car_year", to="EV_rent.caryear", verbose_name="Год"
            ),
        ),
    ]
