# Generated by Django 4.1.6 on 2023-03-29 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("EV_rent", "0013_alter_cars_year"),
    ]

    operations = [
        migrations.RemoveField(model_name="cars", name="year",),
        migrations.AddField(
            model_name="cars",
            name="year",
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
