# Generated by Django 4.1.6 on 2023-03-29 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("EV_rent", "0014_remove_cars_year_cars_year"),
    ]

    operations = [
        migrations.RemoveField(model_name="cars", name="car_brand",),
        migrations.DeleteModel(name="CarYear",),
        migrations.DeleteModel(name="CarBrand",),
        migrations.DeleteModel(name="Cars",),
    ]
