# Generated by Django 4.1.6 on 2023-03-30 20:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        (
            "EV_rent",
            "0015_remove_cars_car_brand_delete_caryear_delete_carbrand_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="car",
            name="car_full_name",
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="rentalrequest",
            name="car_model",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="EV_rent.car"
            ),
        ),
        migrations.AlterField(
            model_name="rentalrequest",
            name="email",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
