# Generated by Django 4.1.6 on 2023-03-30 21:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("EV_rent", "0017_rename_email_rentalrequest_person_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="rentalrequest", name="is_broken",),
        migrations.RemoveField(model_name="rentalrequest", name="is_rented",),
    ]
