# Generated by Django 4.1.6 on 2023-03-30 23:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("EV_rent", "0022_servicehistory_rentalhistory"),
    ]

    operations = [
        migrations.AddField(
            model_name="servicehistory",
            name="date",
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
