# Generated by Django 4.1.6 on 2023-03-31 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("EV_rent", "0023_servicehistory_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="car",
            name="rent_price",
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
